### ISSUE TITLE
array assignment

### ISSUE THREAD

**Issue by aimeirak** [Sheila1Noella/Javascript-exercises#2]
ejo uzakora kuri array
kora array uyibikemo [1,1001,10,50,600,700]
print length yiyo array
sorting iyi array by ascending order
ongeramo ikintu kuriyi array ukoresheje method push 
reba nimba iyi array i contains 600
removing ikintu kiri kuri index ya 4
searching muriyi array nimba harimo 20 ukoresheje method bita find ukoresheje na foreach loop 
printing data zose ziri muri array ukoresheje forloop

**Comment by aimeirak** [comment]
@Sheila1Noella

**Comment by Sheila1Noella** [comment]
Done
